import { lazy } from 'react';

const CitadellePage = lazy(() => import('./components/maps_components/CitadellePage.jsx'));
const TerminusPage = lazy(() => import('./components/maps_components/TerminusPage.jsx'));
const ReckoningPage = lazy(() => import('./components/maps_components/ReckoningPage.jsx'));

export const BO6MAPS = [
  {
    Name: 'Terminus',
    Image: 'terminus.jpg',
    Link: '/bo6/maps/terminus',
    Component: TerminusPage
  },
  {
    Name: 'Citadelle Des Morts',
    Image: 'citadelle.jpg',
    Link: '/bo6/maps/citadelle',
    Component: CitadellePage
  },
  {
    Name: 'Reckoning',
    Image: 'reckoning.jpg',
    Link: '/bo6/maps/reckoning',
    Component: ReckoningPage
  }
];

export const BO7MAPS = [
  {
    Name: 'Ashes of the Damned',
    Image: 'ashes.jpg',
    State: 'Soon',
    Component: TerminusPage
  },
];

export const GAMES = [
  {
    Name: 'Black Ops 6',
    Image: 'bo6.jpg',
    Link: '/bo6',
  },
  {
    Name: 'Black Ops 7',
    Image: 'bo7.jpg',
    Link: '/bo7',
    State: 'New',
  }
];

export const tableElements = [
  {name:"H", atomic:"001"},
  {name:"HE", atomic:"002"},
  {name:"LI", atomic:"003"},
  {name:"BE", atomic:"004"},
  {name:"B", atomic:"005"},
  {name:"C", atomic:"006"},
  {name:"N", atomic:"007"},
  {name:"O", atomic:"008"},
  {name:"F", atomic:"009"},
  {name:"NE", atomic:"010"},
  {name:"NA", atomic:"011"},
  {name:"MG", atomic:"012"},
  {name:"AL", atomic:"013"},
  {name:"SI", atomic:"014"},
  {name:"P", atomic:"015"},
  {name:"S", atomic:"016"},
  {name:"CL", atomic:"017"},
  {name:"AR", atomic:"018"},
  {name:"K", atomic:"019"},
  {name:"CA", atomic:"020"},
  {name:"SC", atomic:"021"},
  {name:"TI", atomic:"022"},
  {name:"V", atomic:"023"},
  {name:"CR", atomic:"024"},
  {name:"MN", atomic:"025"},
  {name:"FE", atomic:"026"},
  {name:"CO", atomic:"027"},
  {name:"NI", atomic:"028"},
  {name:"CU", atomic:"029"},
  {name:"ZN", atomic:"030"},
  {name:"GA", atomic:"031"},
  {name:"GE", atomic:"032"},
  {name:"AS", atomic:"033"},
  {name:"SE", atomic:"034"},
  {name:"BR", atomic:"035"},
  {name:"KR", atomic:"036"},
  {name:"RB", atomic:"037"},
  {name:"SR", atomic:"038"},
  {name:"Y", atomic:"039"},
  {name:"ZR", atomic:"040"},
  {name:"NB", atomic:"041"},
  {name:"MO", atomic:"042"},
  {name:"TC", atomic:"043"},
  {name:"RU", atomic:"044"},
  {name:"RH", atomic:"045"},
  {name:"PD", atomic:"046"},
  {name:"AG", atomic:"047"},
  {name:"CD", atomic:"048"},
  {name:"IN", atomic:"049"},
  {name:"SN", atomic:"050"},
  {name:"SB", atomic:"051"},
  {name:"TE", atomic:"052"},
  {name:"I", atomic:"053"},
  {name:"XE", atomic:"054"},
  {name:"CS", atomic:"055"},
  {name:"BA", atomic:"056"},
  {name:"LA", atomic:"057"},
  {name:"CE", atomic:"058"},
  {name:"PR", atomic:"059"},
  {name:"ND", atomic:"060"},
  {name:"PM", atomic:"061"},
  {name:"SM", atomic:"062"},
  {name:"EU", atomic:"063"},
  {name:"GD", atomic:"064"},
  {name:"TB", atomic:"065"},
  {name:"DY", atomic:"066"},
  {name:"HO", atomic:"067"},
  {name:"ER", atomic:"068"},
  {name:"TM", atomic:"069"},
  {name:"YB", atomic:"070"},
  {name:"LU", atomic:"071"},
  {name:"HF", atomic:"072"},
  {name:"TA", atomic:"073"},
  {name:"W", atomic:"074"},
  {name:"RE", atomic:"075"},
  {name:"OS", atomic:"076"},
  {name:"IR", atomic:"077"},
  {name:"PT", atomic:"078"},
  {name:"AU", atomic:"079"},
  {name:"HG", atomic:"080"},
  {name:"TL", atomic:"081"},
  {name:"PB", atomic:"082"},
  {name:"BI", atomic:"083"},
  {name:"PO", atomic:"084"},
  {name:"AT", atomic:"085"},
  {name:"RN", atomic:"086"},
  {name:"FR", atomic:"087"},
  {name:"RA", atomic:"088"},
  {name:"AC", atomic:"089"},
  {name:"TH", atomic:"090"},
  {name:"PA", atomic:"091"},
  {name:"U", atomic:"092"},
  {name:"NP", atomic:"093"},
  {name:"PU", atomic:"094"},
  {name:"AM", atomic:"095"},
  {name:"CM", atomic:"096"},
  {name:"BK", atomic:"097"},
  {name:"CF", atomic:"098"},
  {name:"ES", atomic:"099"},
  {name:"FM", atomic:"100"},
  {name:"MD", atomic:"101"},
  {name:"NO", atomic:"102"},
  {name:"LR", atomic:"103"},
  {name:"RF", atomic:"104"},
  {name:"DB", atomic:"105"},
  {name:"SG", atomic:"106"},
  {name:"BH", atomic:"107"},
  {name:"HS", atomic:"108"},
  {name:"MT", atomic:"109"},
  {name:"DS", atomic:"110"},
  {name:"RG", atomic:"111"},
  {name:"CN", atomic:"112"},
  {name:"NH", atomic:"113"},
  {name:"FL", atomic:"114"},
  {name:"MC", atomic:"115"},
  {name:"LV", atomic:"116"},
  {name:"TS", atomic:"117"},
  {name:"OG", atomic:"118"}
];